name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: read

jobs:
  ci:
    uses: matt-riley/matt-riley-ci/.github/workflows/ci.yml@v1
    with:
      install: true
      lint: true
      build: true
      test: true
      fmt: true
